# Generated by Django 2.0.6 on 2018-11-09 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Esta respuesta puede ser de texto abierto, un numero, un booleano,            o un id de una respuesta', verbose_name='Respueta')),
                ('choice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id de la respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria de seguro',
                'verbose_name_plural': 'Categoria de seguros',
            },
        ),
        migrations.CreateModel(
            name='DocumentsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_card', models.ImageField(blank=True, upload_to='Solicitudes/tarjetas', verbose_name='Imagen')),
                ('drive_license', models.ImageField(blank=True, upload_to='Solicitudes/licencias', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Documento de la solicitud',
                'verbose_name_plural': 'Documentos de la solicitud',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seguros/images/', verbose_name='Imagen del seguro')),
                ('min_value_prima', models.IntegerField(blank=True, null=True, verbose_name='Valor mínimo de la prima')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la covertura')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='Valor mínimo de la cobertura')),
                ('is_required', models.BooleanField(default=False, verbose_name='Es requerido?')),
            ],
            options={
                'verbose_name': 'Cobertura del seguro',
                'verbose_name_plural': 'Coberturas del seguro',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser_code', models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=15, verbose_name='Codigo asesor')),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('EX', 'Vencido'), ('PR', 'En proceso'), ('AP', 'Aprobado'), ('CU', 'Vigente')], default='PE', max_length=2, verbose_name='Estado')),
                ('request_date', models.DateField(verbose_name='Fecha de solicitud')),
            ],
            options={
                'verbose_name': 'Historial solicitud',
                'verbose_name_plural': 'Historial solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numerico'), ('checkbox', 'Booleano'), ('image', 'Imagen'), ('select', 'Seleccion')], max_length=10, verbose_name='Tipo del campo')),
                ('is_required', models.BooleanField(default=True, verbose_name='Es requerido?')),
            ],
            options={
                'verbose_name': 'Campo del seguro',
                'verbose_name_plural': 'Campos de los seguros',
            },
        ),
        migrations.CreateModel(
            name='MetadataChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Opcion del campo',
                'verbose_name_plural': 'Opciones del campo',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('code', models.CharField(max_length=10, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Punto autorizado',
                'verbose_name_plural': 'Puntos autorizados',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría de seguro',
                'verbose_name_plural': 'Subcategorías de seguros',
            },
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_file', models.FileField(blank=True, upload_to='Polizas', verbose_name='Documento del seguro')),
                ('licensed_plate', models.CharField(default='###-###', max_length=8, verbose_name='placa')),
                ('adviser_mail', models.EmailField(blank=True, help_text='Agregar en caso de que aplique', max_length=254, verbose_name='Correo asesor')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio de vigencia')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('insurance_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Póliza del cliente')),
                ('insurer', models.ForeignKey(help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora')),
            ],
            options={
                'verbose_name': 'Póliza cliente',
                'verbose_name_plural': 'Póliza clientes',
            },
        ),
    ]
