# Generated by Django 2.0.6 on 2018-11-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_insurancerequest_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio del seguro SOAT (Si aplica)'),
        ),
    ]
