# Generated by Django 2.0.6 on 2018-11-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_insurancerequest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio del seguro SOAT (Si aplica)'),
        ),
    ]
