# Generated by Django 2.0.6 on 2018-12-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0013_userpolicy_adviser_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomiRequestInsurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion de recogida')),
                ('pickup_date', models.DateField(verbose_name='Dia de recogida')),
                ('pickup_time', models.TimeField(verbose_name='Hora de recogida')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Número de contacto')),
                ('request_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Solicitud del seguro')),
            ],
        ),
    ]
