# Generated by Django 2.0.6 on 2018-12-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0014_domirequestinsurer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domirequestinsurer',
            options={'verbose_name': 'Solicitud de Domicilio', 'verbose_name_plural': 'Solicitudes de Domicilio'},
        ),
        migrations.RemoveField(
            model_name='domirequestinsurer',
            name='contact_phone',
        ),
    ]
