# Generated by Django 2.0.6 on 2018-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0015_auto_20181219_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='old_insurance',
            field=models.BooleanField(default=False, verbose_name='Seguro antiguo?'),
        ),
    ]
