# Generated by Django 2.1.1 on 2018-09-05 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Número de celular')),
                ('logo', models.ImageField(blank=True, upload_to='logotipos', verbose_name='Imagen')),
                ('user', models.OneToOneField(help_text='Enlace al usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Número de celular')),
                ('document_type', models.CharField(help_text='Tipo de documento de identidad', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=15, verbose_name='Numero de documento')),
                ('user', models.OneToOneField(blank=True, help_text='Enlace al usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptanceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceptance_date', models.DateField(verbose_name='Fecha de solicitud')),
                ('ip_address', models.CharField(max_length=20, verbose_name='IP de aceptacion del cliente')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Cliente')),
            ],
        ),
    ]
