# Generated by Django 2.0.6 on 2018-10-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsacceptancelogs',
            options={'verbose_name': 'Log de Términos', 'verbose_name_plural': 'Logs de términos'},
        ),
    ]
