# Generated by Django 2.0 on 2018-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_auto_20180815_2128'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='insurer',
            field=models.ManyToManyField(help_text='Enlace a la aseguradora', to='insurances.Insurer', verbose_name='Aseguradora'),
        ),
    ]
