# Generated by Django 2.0.8 on 2018-08-20 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_authorizedpoint_customerpolicy_historyrequestinsurance_insurer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Número de celular')),
                ('insurances', models.ManyToManyField(to='insurances.Insurance', verbose_name='Seguros')),
                ('user', models.OneToOneField(help_text='Enlace al usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Número de celular')),
                ('document_type', models.CharField(help_text='Tipo de documento de identidad', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=15, verbose_name='Numero de documento')),
                ('user', models.OneToOneField(help_text='Enlace al usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
