# Generated by Django 2.0.6 on 2018-09-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180906_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
