# Generated by Django 2.0.6 on 2018-09-16 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20180906_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de extrajería')], help_text='Tipo de documento de identidad', max_length=2, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=15, verbose_name='Numero de documento')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número telefónico')),
                ('bank', models.CharField(max_length=255, verbose_name='Banco')),
                ('account_type', models.CharField(choices=[('AH', 'Ahorros'), ('CO', 'Corriente')], max_length=2, verbose_name='Tipo de cuenta bancaria')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de cuenta bancaria')),
                ('code', models.CharField(max_length=15, verbose_name='Código de influencer')),
                ('user', models.OneToOneField(blank=True, help_text='Enlace al usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de extrajería')], help_text='Tipo de documento de identidad', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
