# Generated by Django 2.0 on 2018-08-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_broker_insurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='insurer',
        ),
    ]
