# Generated by Django 2.0 on 2018-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_insurer_brokers'),
        ('users', '0003_remove_broker_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='insurances',
            field=models.ManyToManyField(to='insurances.Insurance', verbose_name='Seguros'),
        ),
    ]
