# Generated by Django 2.0.6 on 2018-09-17 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20180916_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsacceptancelogs',
            name='customer',
        ),
        migrations.AddField(
            model_name='termsacceptancelogs',
            name='user',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termsacceptancelogs',
            name='Acceptance_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
    ]
