# Generated by Django 2.0 on 2018-08-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_broker_insurances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
