# Generated by Django 2.0 on 2018-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180822_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logotipos', verbose_name='Imagen'),
        ),
    ]
