# Generated by Django 2.0.6 on 2019-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Texto')),
                ('police_type', models.CharField(choices=[('TC', 'Términos y condiciones'), ('PP', 'Políticas de privacidad')], max_length=2, unique=True, verbose_name='Tipo de Política')),
            ],
            options={
                'verbose_name': 'Politica',
            },
        ),
    ]
