# Generated by Django 2.0.6 on 2018-09-17 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_card', models.ImageField(blank=True, upload_to='Solicitudes/tarjetas', verbose_name='Imagen')),
                ('drive_license', models.ImageField(blank=True, upload_to='Solicitudes/licencias', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria de seguro',
                'verbose_name_plural': 'Categoria de seguros',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser_code', models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=15, verbose_name='Codigo asesor')),
                ('state', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('AP', 'Aprobado')], default='PE', max_length=2, verbose_name='Estado')),
                ('request_date', models.DateField(verbose_name='Fecha de solicitud')),
            ],
            options={
                'verbose_name': 'Historial solicitud',
                'verbose_name_plural': 'Historial solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('code', models.CharField(max_length=10, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Punto autorizado',
                'verbose_name_plural': 'Puntos autorizados',
            },
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Polizas', verbose_name='Imagen')),
                ('adviser_code', models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=15, verbose_name='Codigo asesor')),
                ('licensed_plate', models.CharField(default='###-###', max_length=8, verbose_name='placa')),
                ('adviser_mail', models.EmailField(blank=True, help_text='Agregar en caso de que aplique', max_length=254, verbose_name='Correo asesor')),
                ('expiration_date', models.DateField(default=datetime.datetime(2019, 9, 18, 19, 12, 10, 403554, tzinfo=utc), verbose_name='Fecha de vencimiento')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio de vigencia')),
                ('insurance', models.ForeignKey(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro')),
                ('insurer', models.ForeignKey(help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora')),
            ],
            options={
                'verbose_name': 'Póliza cliente',
                'verbose_name_plural': 'Póliza clientes',
            },
        ),
    ]
