# Generated by Django 2.1.1 on 2018-09-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Polizas', verbose_name='Imagen')),
                ('adviser_code', models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=15, verbose_name='Codigo asesor')),
                ('adviser_mail', models.EmailField(blank=True, help_text='Agregar en caso de que aplique', max_length=254, verbose_name='Correo asesor')),
                ('effective_date', models.DateField(editable=False, verbose_name='Fecha de vigencia')),
            ],
            options={
                'verbose_name': 'Póliza cliente',
                'verbose_name_plural': 'Póliza clientes',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria de seguro',
                'verbose_name_plural': 'Categoria de seguros',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('AP', 'Aprobado')], default='PE', max_length=2, verbose_name='Estado')),
                ('request_date', models.DateField(verbose_name='Fecha de solicitud')),
                ('broker', models.OneToOneField(help_text='Enlace al corredor', on_delete=django.db.models.deletion.CASCADE, to='users.Broker', verbose_name='Corredor')),
                ('customer', models.OneToOneField(help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Cliente')),
                ('insurance', models.OneToOneField(help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro')),
            ],
            options={
                'verbose_name': 'Historial solicitud',
                'verbose_name_plural': 'Historial solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('active', models.BooleanField(default=True)),
                ('brokers', models.ManyToManyField(to='users.Broker', verbose_name='Corredores')),
                ('insurances', models.ManyToManyField(to='insurances.Insurance', verbose_name='Seguros')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('code', models.CharField(max_length=10, verbose_name='Codigo')),
                ('brokers', models.ManyToManyField(to='users.Broker', verbose_name='Corredores')),
            ],
            options={
                'verbose_name': 'Punto autorizado',
                'verbose_name_plural': 'Puntos autorizados',
            },
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='point_of_sale',
            field=models.OneToOneField(help_text='Enlace al punto autorizado', on_delete=django.db.models.deletion.CASCADE, to='insurances.PointOfSale', verbose_name='Punto Autorizado'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='category',
            field=models.OneToOneField(help_text='Enlace a la categoria del seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceCategory', verbose_name='Categoria seguro'),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='insurance',
            field=models.ForeignKey(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='insurer',
            field=models.ForeignKey(help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora'),
        ),
    ]
