# Generated by Django 2.0.8 on 2018-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('code', models.CharField(max_length=10, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Punto autorizado',
                'verbose_name_plural': 'Puntos autorizados',
            },
        ),
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagen')),
                ('adviser_code', models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=15, verbose_name='Codigo asesor')),
                ('adviser_mail', models.EmailField(blank=True, help_text='Agregar en caso de que aplique', max_length=254, verbose_name='Correo asesor')),
                ('effective_date', models.DateField(editable=False, verbose_name='Fecha de vigencia')),
            ],
            options={
                'verbose_name': 'Póliza cliente',
                'verbose_name_plural': 'Póliza clientes',
            },
        ),
        migrations.CreateModel(
            name='HistoryRequestInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('AP', 'Aprobado')], default='PE', max_length=2, verbose_name='Estado')),
                ('request_date', models.DateField(default=None, verbose_name='Fecha de solicitud')),
            ],
            options={
                'verbose_name': 'Historial solicitud',
                'verbose_name_plural': 'Historial solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cellphone_number', models.CharField(default=None, max_length=13, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
    ]
