# Generated by Django 2.0 on 2018-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
