# Generated by Django 2.0.6 on 2018-09-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Corredores'),
        ),
        migrations.AddField(
            model_name='insurer',
            name='insurances',
            field=models.ManyToManyField(to='insurances.Insurance', verbose_name='Seguros'),
        ),
        migrations.AddField(
            model_name='insurer',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Corredores'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='brokers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='related_insurances_broker', to=settings.AUTH_USER_MODEL, verbose_name='Corredores'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='client',
            field=models.ForeignKey(help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, related_name='related_insurances_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='insurance',
            field=models.ForeignKey(help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='category',
            field=models.ForeignKey(help_text='Enlace a la categoria del seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceCategory', verbose_name='Categoria seguro'),
        ),
        migrations.AddField(
            model_name='documentsrequest',
            name='insurance_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Solicitud'),
        ),
    ]
