# Generated by Django 2.0.6 on 2018-09-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_auto_20180906_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerequest',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='insurancerequest',
            name='point_of_sale',
        ),
    ]
