# Generated by Django 2.0 on 2018-08-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_insurance_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Seguro de usuario',
                'verbose_name_plural': 'Seguros de usuario',
            },
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='insurance',
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insurer',
            options={},
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='insurance',
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(default=None, help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='insurer',
            name='cellphone_number',
            field=models.CharField(default=None, max_length=13, verbose_name='Numero de celular'),
        ),
        migrations.AlterField(
            model_name='categoryinsurance',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='category',
            field=models.OneToOneField(help_text='Enlace a la categoria del seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.CategoryInsurance', verbose_name='Categoria seguro'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='InsuranceDocument',
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='insurance',
            field=models.OneToOneField(help_text='Enlace a el seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance'),
        ),
    ]
