# Generated by Django 2.0.6 on 2018-11-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_auto_20181108_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de la referencia'),
        ),
    ]
