# Generated by Django 2.0.8 on 2018-08-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_broker_customer'),
        ('insurances', '0002_authorizedpoint_customerpolicy_historyrequestinsurance_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='brokers',
            field=models.ManyToManyField(to='users.Broker', verbose_name='Corredores'),
        ),
        migrations.AddField(
            model_name='insurer',
            name='insurances',
            field=models.ManyToManyField(to='insurances.Insurance', verbose_name='Seguros'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='authorized_point',
            field=models.OneToOneField(default=None, help_text='Enlace al punto autorizado', on_delete=django.db.models.deletion.CASCADE, to='insurances.AuthorizedPoint', verbose_name='Punto Autorizado'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='broker',
            field=models.OneToOneField(default=None, help_text='Enlace al corredor', on_delete=django.db.models.deletion.CASCADE, to='users.Broker', verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='customer',
            field=models.OneToOneField(default=None, help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='insurance',
            field=models.OneToOneField(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='insurance',
            field=models.ForeignKey(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='insurer',
            field=models.ForeignKey(help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='authorizedpoint',
            name='brokers',
            field=models.ManyToManyField(to='users.Broker', verbose_name='Corredores'),
        ),
    ]
