# Generated by Django 2.0.6 on 2018-09-22 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_auto_20180917_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancerequest',
            old_name='brokers',
            new_name='broker',
        ),
        migrations.RenameField(
            model_name='insurancerequest',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 23, 19, 51, 20, 394222, tzinfo=utc), verbose_name='Fecha de vencimiento'),
        ),
    ]
