# Generated by Django 2.0.6 on 2018-11-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_insurancerequest_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='Solicitudes/SOAT/recibos', verbose_name='Recibo de pago SOAT (si aplica)'),
        ),
    ]
