# Generated by Django 2.0.8 on 2018-08-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_auto_20180820_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyrequestinsurance',
            options={'permissions': (('read_history', 'Can read HistoryRequestInsurance'),), 'verbose_name': 'Historial solicitud', 'verbose_name_plural': 'Historial solicitudes'},
        ),
    ]
