# Generated by Django 2.0.6 on 2018-09-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_auto_20180907_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_card', models.ImageField(blank=True, upload_to='Solicitudes/tarjetas', verbose_name='Imagen')),
                ('drive_license', models.ImageField(blank=True, upload_to='Solicitudes/licencias', verbose_name='Imagen')),
                ('insurance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Solicitud')),
            ],
        ),
    ]
