# Generated by Django 2.0.6 on 2018-09-29 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_auto_20180922_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsrequest',
            options={'verbose_name': 'Documento de la solicitud', 'verbose_name_plural': 'Documentos de la solicitud'},
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='adviser_code',
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='user',
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='insurance_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Póliza del cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurancerequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EX', 'Vencido'), ('PR', 'En proceso'), ('AP', 'Aprobado'), ('CU', 'Vigente')], default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='expiration_date',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
    ]
