# Generated by Django 2.0 on 2018-08-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('insurances', '0003_auto_20180815_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryInsurance',
            new_name='InsuranceCategory',
            
        ),
        migrations.AlterModelOptions(
            name='insurancecategory',
            options={'verbose_name': 'Categoria de seguro', 'verbose_name_plural': 'Categoria de seguros'},
        ),
    ]
