# Generated by Django 2.0.8 on 2018-08-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_auto_20180820_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyrequestinsurance',
            options={'verbose_name': 'Historial solicitud', 'verbose_name_plural': 'Historial solicitudes'},
        ),
    ]
