# Generated by Django 2.0 on 2018-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_broker_insurer'),
        ('insurances', '0004_auto_20180815_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='brokers',
            field=models.ManyToManyField(to='users.Broker', verbose_name='Corredores'),
        ),
    ]
