# Generated by Django 2.0.6 on 2018-11-07 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_auto_20180930_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Esta respuesta puede ser de texto abierto, un numero, un booleano,            o un id de una respuesta', verbose_name='Respueta')),
                ('choice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id de la respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numerico'), ('checkbox', 'Booleano'), ('image', 'Imagen'), ('select', 'Seleccion')], max_length=10, verbose_name='Tipo del campo')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_field_choices', to='insurances.Metadata', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Opcion de la Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Subcategoría de seguro',
                'verbose_name_plural': 'Subcategorías de seguros',
            },
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='insurer',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='insurance',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='seguros/images/', verbose_name='Imagen del seguro'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='min_value_prima',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor mínimo de la prima'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='category',
            field=models.ForeignKey(help_text='Categoria del seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Subcategory', verbose_name='Categoria seguro'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='insurancerequest',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_insurances_broker', to=settings.AUTH_USER_MODEL, verbose_name='Corredores'),
        ),
        migrations.RenameModel(
            old_name='InsuranceCategory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.Category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='answer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.Metadata', verbose_name='Campo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='insurance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('insurance_request', 'field')},
        ),
    ]
