# Generated by Django 2.0.6 on 2018-09-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_documentsrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='customer',
            field=models.ForeignKey(help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Cliente'),
        ),
    ]
