# Generated by Django 2.0 on 2018-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_insurer_brokers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='insurer',
        ),
        migrations.AddField(
            model_name='insurer',
            name='insurances',
            field=models.ManyToManyField(to='insurances.Insurance', verbose_name='Seguros'),
        ),
    ]
