# Generated by Django 2.0.6 on 2018-09-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_auto_20180909_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='insurance',
            field=models.ForeignKey(help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
    ]
