# Generated by Django 2.0.6 on 2018-10-01 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_auto_20180929_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='insurance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.InsuranceRequest', verbose_name='Póliza del cliente'),
        ),
    ]
