# Generated by Django 2.0.6 on 2018-11-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_auto_20181106_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la covertura')),
                ('min_value', models.IntegerField(verbose_name='Valor mínimo de la cobertura')),
                ('is_required', models.BooleanField(default=False, verbose_name='Es requerido?')),
            ],
            options={
                'verbose_name': 'Cobertura del seguro',
                'verbose_name_plural': 'Coberturas del seguro',
            },
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Campo del seguro', 'verbose_name_plural': 'Campos de los seguros'},
        ),
        migrations.AlterModelOptions(
            name='metadatachoices',
            options={'verbose_name': 'Opcion del campo', 'verbose_name_plural': 'Opciones del campo'},
        ),
        migrations.AlterField(
            model_name='insurance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AddField(
            model_name='insurancecoverage',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
    ]
