# Generated by Django 2.0 on 2018-08-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_broker_insurances'),
        ('insurances', '0006_auto_20180816_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('cellphone_number', models.CharField(max_length=13, verbose_name='Numero de celular')),
                ('code', models.CharField(max_length=10, verbose_name='Codigo')),
                ('brokers', models.ManyToManyField(to='users.Broker', verbose_name='Corredores')),
            ],
            options={
                'verbose_name_plural': 'Puntos autorizados',
                'verbose_name': 'Punto autorizado',
            },
        ),
        migrations.CreateModel(
            name='HistoryRequestInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
