# Generated by Django 2.0.6 on 2018-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0006_auto_20181107_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecoverage',
            name='min_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor mínimo de la cobertura'),
        ),
    ]
