# Generated by Django 2.0.6 on 2018-11-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0007_userpolicy_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='insurance',
            field=models.ForeignKey(blank=True, help_text='Seguro', null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AlterField(
            model_name='insurancerequest',
            name='insurance',
            field=models.ForeignKey(help_text='Seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
    ]
