# Generated by Django 2.0 on 2018-08-16 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_broker_insurances'),
        ('insurances', '0007_authorizedpoint_historyrequestinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='authorized_point',
            field=models.OneToOneField(default=None, help_text='Enlace al punto autorizado', on_delete=django.db.models.deletion.CASCADE, to='insurances.AuthorizedPoint'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='broker',
            field=models.OneToOneField(default=None, help_text='Enlace al corredor', on_delete=django.db.models.deletion.CASCADE, to='users.Broker'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='customer',
            field=models.OneToOneField(default=None, help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='effective_date',
            field=models.DateField(default=None, verbose_name='Fecha de vigencia'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='insurance',
            field=models.OneToOneField(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='insurer',
            field=models.OneToOneField(default=None, help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='request_date',
            field=models.DateField(default=None, verbose_name='Fecha de solicitud'),
        ),
        migrations.AddField(
            model_name='historyrequestinsurance',
            name='state',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('AP', 'Aprobado')], default='PE', max_length=2),
        ),
    ]
