# Generated by Django 2.0 on 2018-08-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_auto_20180816_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrequestinsurance',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='historyrequestinsurance',
            name='insurer',
        ),
        migrations.AlterField(
            model_name='historyrequestinsurance',
            name='authorized_point',
            field=models.OneToOneField(default=None, help_text='Enlace al punto autorizado', on_delete=django.db.models.deletion.CASCADE, to='insurances.AuthorizedPoint', verbose_name='Punto Autorizado'),
        ),
        migrations.AlterField(
            model_name='historyrequestinsurance',
            name='broker',
            field=models.OneToOneField(default=None, help_text='Enlace al corredor', on_delete=django.db.models.deletion.CASCADE, to='users.Broker', verbose_name='Corredor'),
        ),
        migrations.AlterField(
            model_name='historyrequestinsurance',
            name='customer',
            field=models.OneToOneField(default=None, help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historyrequestinsurance',
            name='insurance',
            field=models.OneToOneField(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AlterField(
            model_name='historyrequestinsurance',
            name='state',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('AP', 'Aprobado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
