# Generated by Django 2.0.6 on 2018-09-16 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_auto_20180911_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpolicy',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 17, 16, 35, 38, 816358, tzinfo=utc), verbose_name='Fecha de vencimiento'),
        ),
    ]
