# Generated by Django 2.0.6 on 2018-11-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_auto_20181107_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_metadata', to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AlterField(
            model_name='metadatachoices',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_choices', to='insurances.Metadata', verbose_name='Campo'),
        ),
    ]
