# Generated by Django 2.0.6 on 2018-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_auto_20181205_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='taker_document',
            field=models.CharField(blank=True, help_text='Opcional', max_length=20, null=True, verbose_name='Documento de identidad del tomador'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='taker_number',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, verbose_name='Nombre del tomador'),
        ),
    ]
