# Generated by Django 2.0 on 2018-08-17 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_auto_20180817_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('insurance', models.OneToOneField(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro')),
                ('insurer', models.OneToOneField(help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora')),
            ],
        ),
    ]
