# Generated by Django 2.0.6 on 2018-11-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_auto_20181107_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Es requerido?'),
        ),
    ]
