# Generated by Django 2.0.6 on 2018-09-17 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_auto_20180916_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpolicy',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 4, 23, 55, 632039, tzinfo=utc), verbose_name='Fecha de vencimiento'),
        ),
    ]
