# Generated by Django 2.0.6 on 2018-12-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0010_auto_20181205_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpolicy',
            old_name='taker_number',
            new_name='taker_name',
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='licensed_plate',
            field=models.CharField(blank=True, default='###-###', max_length=8, null=True, verbose_name='placa'),
        ),
    ]
