# Generated by Django 2.0 on 2018-08-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0011_auto_20180817_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpolicy',
            name='effective_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de vigencia'),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='insurance',
            field=models.ForeignKey(default=None, help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro'),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='insurer',
            field=models.ForeignKey(help_text='Enlace a la aseguradora', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurer', verbose_name='Aseguradora'),
        ),
    ]
