# Generated by Django 2.0.6 on 2018-12-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0011_auto_20181205_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpolicy',
            name='taker_document',
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='taker_name',
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='insurance_file',
            field=models.FileField(blank=True, null=True, upload_to='Polizas', verbose_name='Documento del seguro'),
        ),
    ]
