# Generated by Django 2.0 on 2018-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0012_auto_20180817_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolicy',
            name='adviser_code',
            field=models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=15, verbose_name='Codigo asesor'),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='adviser_mail',
            field=models.EmailField(blank=True, help_text='Agregar en caso de que aplique', max_length=254, verbose_name='Correo asesor'),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='effective_date',
            field=models.DateField(editable=False, verbose_name='Fecha de vigencia'),
        ),
    ]
