# Generated by Django 2.0.6 on 2018-12-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0012_auto_20181206_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='adviser_cellphone',
            field=models.CharField(blank=True, help_text='Agregar en caso de que aplique', max_length=255, verbose_name='Celular asesor'),
        ),
    ]
