# Generated by Django 2.0 on 2018-08-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0015_insurer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
