# Generated by Django 2.0 on 2018-08-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_broker_logo'),
        ('insurances', '0017_auto_20180822_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En proceso'), ('AP', 'Aprobado')], default='PE', max_length=2, verbose_name='Estado')),
                ('request_date', models.DateField(verbose_name='Fecha de solicitud')),
                ('broker', models.OneToOneField(help_text='Enlace al corredor', on_delete=django.db.models.deletion.CASCADE, to='users.Broker', verbose_name='Corredor')),
                ('customer', models.OneToOneField(help_text='Enlace al cliente', on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Cliente')),
                ('insurance', models.OneToOneField(help_text='Enlace al seguro', on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance', verbose_name='Seguro')),
            ],
            options={
                'verbose_name': 'Historial solicitud',
                'verbose_name_plural': 'Historial solicitudes',
            },
        ),
        migrations.RemoveField(
            model_name='historyrequestinsurance',
            name='authorized_point',
        ),
        migrations.RemoveField(
            model_name='historyrequestinsurance',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='historyrequestinsurance',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historyrequestinsurance',
            name='insurance',
        ),
        migrations.AlterField(
            model_name='insurer',
            name='cellphone_number',
            field=models.CharField(max_length=13, verbose_name='Numero de celular'),
        ),
        migrations.RenameModel(
            old_name='AuthorizedPoint',
            new_name='PointOfSale',
        ),
        migrations.DeleteModel(
            name='HistoryRequestInsurance',
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='point_of_sale',
            field=models.OneToOneField(help_text='Enlace al punto autorizado', on_delete=django.db.models.deletion.CASCADE, to='insurances.PointOfSale', verbose_name='Punto Autorizado'),
        ),
    ]
